### ISSUE TITLE
Can not act as we expected ON ARM platform.

### ISSUE THREAD

**Issue by RingsC** [stewartsmith/libeatmydata#16]
Run the eatmydata as following On ARM, it not act as we expected.  
it seems that mysqld blocked at waiting acquiring mutex.
LD_PRELOAD=/root/libeatmydata-master/.libs/libeatmydata.so  ./mtr innodb.innodb-lock

when i attach to mysqld. the call stack as following:
```
#0  0x0000ffff8a99616c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000ffff8a98f048 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x0000000001e80ad8 in malloc_mutex_lock_final (mutex=0x2f0b600 <init_lock>) at /root/network_test/xxsql/extra/jemalloc/include/jemalloc/internal/mutex.h:155
#3  jemalloc_internal_je_malloc_mutex_lock_slow (mutex=mutex@entry=0x2f0b600 <init_lock>) at /root/network_test/xxsql/extra/jemalloc/src/mutex.c:85
#4  0x0000000001e4dbe0 in malloc_mutex_lock (mutex=0x2f0b600 <init_lock>, tsdn=0x0) at /root/network_test/xxsql/extra/jemalloc/include/jemalloc/internal/mutex.h:221
#5  malloc_init_hard () at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:1673
#6  0x0000000001e51e38 in malloc_init () at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:221
#7  imalloc_init_check (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2153
#8  imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2184
#9  calloc (num=1, size=32) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2416
#10 0x0000ffff8a8fb8a4 in _dlerror_run () from /lib64/libdl.so.2
#11 0x0000ffff8a8fb280 in dlsym () from /lib64/libdl.so.2
#12 0x0000ffff8a9eba00 in eatmydata_init () at libeatmydata/libeatmydata.c:91
#13 0x0000ffff8a9ebdc4 in eatmydata_is_hungry () at libeatmydata/libeatmydata.c:112
#14 open (pathname=0xffffd3f28100 "\360\362\327\002", pathname@entry=0x25d4de0 "/sys/kernel/mm/transparent_hugepage/enabled", flags=-8, flags@entry=0)
    at libeatmydata/libeatmydata.c:174
#15 0x0000000001e81a7c in init_thp_state () at /root/network_test/xxsql/extra/jemalloc/src/pages.c:567
#16 jemalloc_internal_je_pages_boot () at /root/network_test/xxsql/extra/jemalloc/src/pages.c:631
#17 0x0000000001e4c894 in malloc_init_hard_a0_locked () at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:1452
#18 0x0000000001e4d914 in malloc_init_hard () at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:1684
#19 0x0000000001e50ac4 in malloc_init () at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:221
#20 imalloc_init_check (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2153
#21 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2184
#22 jemalloc_internal_je_malloc_default (size=72704) at /root/network_test/xxsql/extra/jemalloc/src/jemalloc.c:2213
#23 0x0000ffff8a79fd44 in ?? () from /lib64/libstdc++.so.6
#24 0x0000ffff8a9d0fbc in call_init.part () from /lib64/ld-linux-aarch64.so.1
#25 0x0000ffff8a9d10c0 in _dl_init () from /lib64/ld-linux-aarch64.so.1
#26 0x0000ffff8a9c4284 in _dl_start_user () from /lib64/ld-linux-aarch64.so.1
```
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

from the callstack, we can see that it's waiting at __lll_lock_wait() when calling pthread_mutex_lock(). 
so that i print out the mutex value : 

(gdb) p *mutex
$1 = {{{prof_data = {tot_wait_time = {ns = 0}, max_wait_time = {ns = 0}, n_wait_times = 0, n_spin_acquired = 0, max_n_thds = 0, n_waiting_thds = {repr = 1}, n_owner_switches = 0, 
        prev_owner = 0x0, n_lock_ops = 1}, lock = {__data = {__lock = 2, __count = 0, __owner = 12819, __nusers = 1, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
        __size = "\002\000\000\000\000\000\000\000\023\062\000\000\001", '\000' <repeats 34 times>, __align = 2}, locked = {repr = false}}, witness = {name = 0x0, rank = 0, 
      comp = 0x0, opaque = 0x0, link = {qre_next = 0x100000000, qre_prev = 0x0}}, lock_order = malloc_mutex_rank_exclusive}}

Does any one meet the same problem as i do ? Thanks in advance. 

BTW: we use jemalloc to instead of glibc malloc primitive.

**Comment by RingsC** [comment]
Does 'dlsym' call failed lead to this dead lock? At call stack frame 11, 10,  '_dlerror_run'  is called because it's called when 'dlsym' execution failed.

**Comment by RingsC** [comment]
I found the why the deak lock occurs. so close this issue. Thanks all.
